apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gradle-cache.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gradle-cache.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-controller
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: nginx
      ports:
        - protocol: TCP
          port: 5071
  egress: []
